#include "taylor2dv.h"

/***********************************************************************
 *
 * Code generated by the TAYLOR translator.
 */

#define _N_DIM_ 20







/*
next line defines the largest power of 2 such that 2^(LEXP2) and
2^(-LEXP2) do not overflow/underflow the double arithmetic of your
computer.
*/
#define LEXP2 1023 

#define DEBUG_LEVEL 0 /* to print some internal information */

int taylor_step_rtbp2dv(MY_FLOAT *ti,
                 MY_FLOAT *x,
                 int      dir,
                 int      step_ctl,
                 double   log10abserr,
                 double   log10relerr,
                 MY_FLOAT *endtime,
                 MY_FLOAT *ht,
                 int      *order)
/*
 * single integration step with taylor method. the parameters are:
 *
 * ti: on input:  time of the initial condition
 *     on output: new time
 *
 * x:  on input:  initial condition
 *     on output: new condition, corresponding to the (output) time ti
 *
 * dir: flag to integrate forward or backwards.
 *     1: forward
 *    -1: backwards
 *     WARNING: this flag is ignored if step_ctl (see below) is set to 0.
 *
 * step_ctl: flag for the step size control. the possible values are:
 *     0: no step size control, so the step and order are provided by
 *        the user. the parameter ht is used as step, and the parameter
 *        order (see below) is used as the order.
 *     1: standard stepsize control. it uses an approximation to the
 *        optimal order and to the radius of convergence of the series
 *        to approximate the 'optimal' step size. It tries to keep
 *        either the absolute or the relative errors below the given
 *        values. See the paper for more details.
 *     2: as 1, but adding an extra condition on the stepsize h: the
 *        terms of the series --after being multiplied by the suitable
 *        power of h-- cannot grow.
 *     3: user defined stepsize control. the code has to be included
 *        in the routine compute_timestep_user_defined (you can find
 *        this routine below). The user should also provide code for
 *        the selection of degree (see the function
 *        compute_order_user_defined below).
 *
 * log10abserr: decimal log of the absolute accuracy. the routine
 *     tries to keep either the absolute or the relative errors below
 *     the given thresholds.
 *
 * log10relerr: decimal log of the relative accuracy. the routine
 *     tries to keep either the absolute or the relative errors below
 *     the given thresholds.
 *
 * endtime: if NULL, it is ignored. if step_ctl (see above) is set
 *     to 0, it is also ignored. otherwise, if the step size is too
 *     large, it is reduced so that the new time ti is exactly endtime
 *     (in that case, the function returns 1).
 *
 * ht: on input:  ignored/used as a time step (see parameter step_ctl)
 *     on output: time step used
 *
 * order: degree of the taylor expansion.
 *        input: this parameter is only used if step_ctl is 0,
 *               or if you add the code for the case step_ctl=3.
 *               its possible values are:
 *               < 2: the program will select degree 2 (if step_ctl is 0).
 *               >=2: the program will use this degree (if step_ctl is 0).
 *        ouput: degree used.
 *
 * return value:
 * 0: ok.
 * 1: ok, and ti=endtime.  */
{
  MY_FLOAT **taylor_coefficients_rtbp2dv(MY_FLOAT, MY_FLOAT*, int);
  MY_FLOAT **taylor_coefficients_rtbp2dvA(MY_FLOAT, MY_FLOAT*, int, int);
  int compute_order_1_rtbp2dv(double, double, double, int*);
  int comp_order_other_rtbp2dv(double, double, double);
  double compute_stepsize_1_rtbp2dv(MY_FLOAT**, int, double, int);
  double compute_stepsize_2_rtbp2dv(MY_FLOAT**, int, double, int);
  double comp_stepsize_other_rtbp2dv(MY_FLOAT**, int, int, double, double, double);

  static MY_FLOAT **s,h,mtmp;
  double xi,xnorm,dh;
  int i,j,k,nt,flag_endtime,flag_err;
  static int init=0;

  if (init == 0) /* initialization of MY_FLOAT variables */
    {
      init=1;
      InitMyFloat(h);
      InitMyFloat(mtmp);
    }
/*
  sup norm of the initial condition
*/
  xnorm=0;
  if (step_ctl != 0)
    {
      for (i=0; i<_N_DIM_; i++)
      {
	MyFloatToDouble(xi,x[i]);
	xi=fabs(xi);
	if (xi > xnorm) xnorm=xi;
      }
    }
/*
  we determine the degree of the taylor expansion.
  this value will be stored in the variable nt.
  the flag flag_err returns a value indicating if we are using an
  absolute error estimate (value 1) or a relative one (value 2).
*/
  switch(step_ctl)
    {
    case 0: /* no step size control, fixed degree; both given by the user */
      nt=(*order<2)? 2: *order; /* 2 is the minimum order allowed */
      break;
    case 1:
      nt=compute_order_1_rtbp2dv(xnorm,log10abserr,log10relerr,&flag_err);
      break;
    case 2:
      nt=compute_order_1_rtbp2dv(xnorm,log10abserr,log10relerr,&flag_err);
      break;
    case 3:
      nt=comp_order_other_rtbp2dv(xnorm,log10abserr,log10relerr);
      break;
    default:
      fprintf(stderr, "taylor_step: undefined step size control.\n");
      fprintf(stderr, "you must choose an existing step size control\n");
      fprintf(stderr, "method or supply a step size control procedure.\n");
      exit(0);
    }
  *order=nt;
/*
  computation of the jet of derivatives up to order nt
*/
  if(step_ctl != 0) {
    s=taylor_coefficients_rtbp2dvA(*ti,x,nt,1);
  } else {
    s=taylor_coefficients_rtbp2dv(*ti,x,nt); 
 }

/*
  selection of the routine to compute the time step. the value
  step_ctl=3 has been reserved for the user, in case she/he wants to
  code a different method.
*/
  switch(step_ctl)
    {
    case 0: /* no step size control (fixed step size, given by the user) */
      AssignMyFloat(h,*ht);
      break;
    case 1:
      dh=compute_stepsize_1_rtbp2dv(s,nt,xnorm,flag_err);
      MakeMyFloatA(h, dh);
      break;
    case 2:
      dh=compute_stepsize_2_rtbp2dv(s,nt,xnorm,flag_err);
      MakeMyFloatA(h, dh);
      break;
    case 3:
      dh=comp_stepsize_other_rtbp2dv(s,_N_DIM_,nt,xnorm,log10abserr,log10relerr);
      MakeMyFloatA(h, dh);
      break;
    default:
      fprintf(stderr, "taylor_step: undefined step size control.\n");
      fprintf(stderr, "You must choose an existing step size control\n");
      fprintf(stderr, "method or supply a step size control procedure.\n");
      exit(0);
    }
/*
  if step_ctl != 0, we adjust the sign of the computed stepsize.
*/
  flag_endtime=0;
  if (step_ctl != 0)
    {
      if (dir == -1) { NegateMyFloatA(mtmp,h); AssignMyFloat(h, mtmp);} 
/*
      we compare *ti+h with endtime. we modify h if necessary.
*/
      if (endtime != NULL)
        {
          AddMyFloatA(mtmp,h,*ti);
          if (dir == 1) /* time goes forward */
            {
              if (MyFloatA_GE_B(mtmp,*endtime))
                {
                  SubstractMyFloatA(h,*endtime,*ti);
                  flag_endtime=1;
                }
            }
            else /* time goes backwards */
            {
              if (MyFloatA_GE_B(*endtime,mtmp))
                {
                  SubstractMyFloatA(h,*endtime,*ti);
                  flag_endtime=1;
                }
            }
        }
    }
/*
  next lines are the summation of the taylor series (horner's method)
*/
  j=nt-1;
  for(i=0; i<_N_DIM_; i++) {AssignMyFloat(x[i],s[i][nt]);}
  for(k=j; k>=0; k--)
  {
    for(i=0; i<_N_DIM_; i++)
    {
      MultiplyMyFloatA(mtmp, h, x[i]);
      AddMyFloatA(x[i], mtmp, s[i][k]);
    }
  }
/*
  finally, we set the values of the parameters *ht and *ti.
*/
  AssignMyFloat(*ht,h);
  if (flag_endtime == 0)
    {
      AssignMyFloat(mtmp, *ti);
      AddMyFloatA(*ti, mtmp, h);
    }
    else
    {
      AssignMyFloat(*ti,*endtime);
    }
  return(flag_endtime);
}
int compute_order_1_rtbp2dv(double xnorm, double log10abserr, double log10relerr, int* flag_err)
/*
 * this is to determine the 'optimal' degree of the taylor expansion.
 *
 * parameters:
 * xnorm: norm of the initial condition
 * log10abserr: base-10 log of the absolute error required
 * log10relerr: base-10 log of the relative error required
 * flag_err:    flag. returns 1 if absolute error is used
 *                    returns 2 if relative error is used
 *
 * returned value: 'optimal' degree.
*/
{
  double log10eps,tmp;
  int nt;

  log10eps=log10abserr;
  *flag_err=1;
  if (xnorm != (double)0.0)
    {
      tmp=log10relerr+log10(xnorm);
      if (tmp > log10abserr) {log10eps=log10relerr; *flag_err=2;}
    }
/*
  we use 1.16 for the value 0.5*log(10)=1.151292546497...
*/
  nt=(int)(1.5-1.16*log10eps);
  if (nt < 2) nt=2; /* this is the minimum order accepted */

#if DEBUG_LEVEL > 0
      fprintf(stderr, "taylor_step: order is %d\n",nt);
#endif

  return(nt);
}
double compute_stepsize_1_rtbp2dv(MY_FLOAT **s, int nt, double xnorm, int flag_err)
/*
 * it looks for a step size for an expansion up to order nt. this
 * function requires that nt is the value computed by
 * compute_order_1_
 */
{
  double double_log_MyFloat_rtbp2dv(MY_FLOAT x);
  static MY_FLOAT z,v1,v2;
  static MY_FLOAT of,uf;
  double lnv1,lnv2,r,lnro1,lnro2,lnro;
  int i;
  static int init=0;

  if (init == 0)
    {
      init=1;
      InitMyFloat(z);
      InitMyFloat(v1);
      InitMyFloat(v2);
      InitMyFloat(of);
      InitMyFloat(uf);

      r=pow((double)2,(double)LEXP2);
      MakeMyFloatA(of,r);
      r=pow((double)2,(double)(-LEXP2));
      MakeMyFloatA(uf,r);
    }
/*
  we compute the sup norm of the last two coefficients of the taylor
  series, and we store them into v1 and v2.
*/
  fabsMyFloatA(v1,s[0][nt-1]);
  fabsMyFloatA(v2,s[0][nt]);
  for(i=1; i<_N_DIM_; i++)
  {
    fabsMyFloatA(z,s[i][nt-1]);
    if (MyFloatA_GT_B(z,v1)) AssignMyFloat(v1,z);
    fabsMyFloatA(z,s[i][nt]);
    if (MyFloatA_GT_B(z,v2)) AssignMyFloat(v2,z);
  }
/*
  computation of the step size. we need the logs of v1 and v2, in
  double precision (there is no need for extended precision). the idea
  is to assign these variables to double variables and then to use the
  standard log function. before doing that, we have to be sure that v1
  can be assigned to a double without under or overflow. for this
  reason we will check for this condition and, if it fails, we will
  call an specific function for this case.
*/
  if (MyFloatA_LE_B(v1,of) && MyFloatA_GE_B(v1,uf))
    {
      MyFloatToDouble(r,v1);
      lnv1=log(r);
    }
    else
    {
      lnv1=double_log_MyFloat_rtbp2dv(v1);
    }
  if (MyFloatA_LE_B(v2,of) && MyFloatA_GE_B(v2,uf))
    {
      MyFloatToDouble(r,v2);
      lnv2=log(r);
    }
    else
    {
      lnv2=double_log_MyFloat_rtbp2dv(v2);
    }
/*
  if flag_err == 2, this means that we are using a relative error control.
*/
  if (flag_err == 2)
    {
      r = -log10(xnorm);
      lnv1 += r;
      lnv2 += r;
    }
 lnro1= -lnv1/(nt-1);
 lnro2= -lnv2/nt;
 lnro=(lnro1 < lnro2)? lnro1: lnro2;

 r=exp(lnro-2-0.7/(nt-1)); /* exp(-0.7/(nt-1)) is a security factor */
  return(r);
}
double compute_stepsize_2_rtbp2dv(MY_FLOAT **s, int nt, double xnorm, int flag_err)
/*
 * it looks for a step size for an expansion up to order nt. this
 * function requires that nt is the value computed by
 * compute_order_1_. it also tries to reduce cancellations of big
 * terms in the summation of the taylor series.
 */
{
  double compute_stepsize_1_rtbp2dv(MY_FLOAT**, int, double, int);
  static MY_FLOAT h,hj,r,z,a,normj;
  double c,rtmp,dh;
  int i,j;
  static int init=0;

  if (init == 0)
    {
      init=1;
      InitMyFloat(h); 
      InitMyFloat(hj);
      InitMyFloat(r);
      InitMyFloat(z);
      InitMyFloat(a);
      InitMyFloat(normj);
    }
/*
  we compute the step size according to the first algorithm
*/
  dh=compute_stepsize_1_rtbp2dv(s,nt,xnorm,flag_err);
  MakeMyFloatA(h,dh);
/*
  next lines select a value (z), that will be used to control the size
  of the terms of the Taylor series.
*/
  if (flag_err == 1) {
     MakeMyFloatA(z, 1.0);
  } else if (flag_err == 2) {
    MakeMyFloatA(z,xnorm);
  } else
    {
      printf("compute_stepsize_2 internal error. flag_err: %d\n",flag_err);
      exit(1);
    }
/*
  next loop checks if the sup norm of the terms in the Taylor series are
  lower than z. if a term is greater than z, the step size h is reduced.
*/
  MakeMyFloatA(hj,(double)1.0);

  for(j=1; j<=nt; j++)
  {
    MultiplyMyFloatA(r,h,hj);
    AssignMyFloat(hj,r);

    MakeMyFloatC(normj,"0", (double)0);
    for (i=0; i<_N_DIM_; i++)
    {
      fabsMyFloatA(a,s[i][j]);
      if (MyFloatA_GT_B(a,normj)) AssignMyFloat(normj,a);
    }

    MultiplyMyFloatA(r,normj,hj);
    if (MyFloatA_LE_B(r,z)) continue;
/*
    we reduce h (and hj)
*/
    DivideMyFloatA(hj,z,normj);

    DivideMyFloatA(a,r,z);
    MyFloatToDouble(c,a);
    c=pow(c,(double)1.e0/(double)j);
    MakeMyFloatA(a,c);
    DivideMyFloatA(r,h,a);
    AssignMyFloat(h,r);

#if DEBUG_LEVEL > 1
    fprintf(stderr, "order %2d. reducing h from %14.6e to %14.6e\n",j,c*h,h);
#endif
  }

  MyFloatToDouble(rtmp,h);
  return(rtmp);
}

double double_log_MyFloat_rtbp2dv(MY_FLOAT x)
/*
 * natural log, in double precision, of a MY_FLOAT positive number.
 */
{
  static MY_FLOAT a,tmp;
  static MY_FLOAT z,of,uf;
  double b,lx;
  int k;
  static int init=0;

  if (init == 0)
    {
      init=1;
      InitMyFloat(a);
      InitMyFloat(z);
      InitMyFloat(of);
      InitMyFloat(uf);
      InitMyFloat(tmp);

      b=0;
      MakeMyFloatA(z,b);
      b=pow((double)2,(double)LEXP2);
      MakeMyFloatA(of,b);
      b=pow((double)2,(double)(-LEXP2));
      MakeMyFloatA(uf,b);
    }

  if (MyFloatA_EQ_B(x,z))
    {
      puts("double_log_MyFloat error: zero argument");
      puts("(this is because one of the last two terms of your taylor");
      puts(" expansion is exactly zero)");
      exit(1);
    }

  AssignMyFloat(a,x);

  k=0;
  while(MyFloatA_LT_B(a,uf))
  {
    ++k;
    if(k>3000){fprintf(stderr,"double_log_MyFloat overflow: %d\n", k); exit(1);}
    MultiplyMyFloatA(tmp,a,of);
    AssignMyFloat(a,tmp);
  }
  while(MyFloatA_GT_B(a,of))
  {
    --k;
    if(k<-3000){fprintf(stderr,"double_log_MyFloat underflow: %d\n", k); exit(1);}
    MultiplyMyFloatA(tmp,a,uf);
    AssignMyFloat(a,tmp);
  }

  MyFloatToDouble(b,a);
/*
  lx stands for log(x)
*/
  lx=log(b)-(LEXP2*0.69314718055994530942)*k;

  return(lx);
}


int comp_order_other_rtbp2dv(double lnxnorm, double log10abserr, double log10relerr){
  puts("---");
  puts("compute_order_user_defined:");
  puts("you have to code this routine");
  puts("or select a different value for the step_ctl parameter");
  puts("---");
  exit(1);

  return(0);
}
double comp_stepsize_other_rtbp2dv(MY_FLOAT **s, int nd, int nt, double xnorm, double log10abserr, double log10relerr) {

  puts("---");
  puts("compute_timestep_user_defined:");
  puts("you have to code this routine");
  puts("or select a different value for the step_ctl parameter");
  puts("---");
  exit(1);
  return((double)0.00001);
}
/***********************************************************************
 *
 * Procedure generated by the TAYLOR translator. Do not edit!
 *
 * It needs the header file 'taylor.h' to compile.
 * Run taylor with the -header -o taylor.h option to generate a sample 'taylor.h'

 * Translation info is at the end of this file.
 * Version 1.4.4, Apr 22, 2008
 ***********************************************************************/

#include <stdio.h>
#include <stdlib.h>
MY_FLOAT **taylor_coefficients_rtbp2dvA(MY_FLOAT t, MY_FLOAT *x, int order, int rflag)
{
   /* input: 
      t:     current value of the time variable 
      x:     array represent values of the state variables
      order: order of the taylor coefficients sought
      rflag: recompute flag. If you call this routine with one order 
             first, but then decided that you need a higher order of the
             taylor polynomial. You can pass 0 to rflag. This routine 
             will try to use the values already computed. Provided that 
             both x and t have not been changed, and you did not modify 
             the jet derivatives from the previous call.
      Return Value:
            Two D Array, rows are the taylor coefficients of the
            state variables

     */
    extern MY_FLOAT mu;

    static int          _jz_ivars[4];
    static MY_FLOAT     _jz_cvars[8];
    static MY_FLOAT     *_jz_jet[114],  *_jz_save = NULL, *_jz_oneOverN=NULL,*_jz_theNs=NULL;
    static MY_FLOAT     _jz_tvar1, _jz_tvar2, _jz_tvar3, _jz_tvar4; /* tmp vars */
    static MY_FLOAT     _jz_uvar1, _jz_uvar2; /* tmp vars */
    static MY_FLOAT     _jz_svar1, _jz_svar2, _jz_svar3, _jz_svar4, _jz_svar5; /* tmp vars */
    static MY_FLOAT     _jz_wvar3, _jz_wvar4; /* tmp vars */
    static MY_FLOAT     _jz_zvar1, _jz_zvar2; /* tmp vars */
    static MY_FLOAT     _jz_MyFloatZERO;
    static int          _jz_maxOrderUsed  = -1;
    static int          _jz_lastOrder = 0, _jz_initialized=0, _jz_ginitialized=0;
    int                 _jz_i, _jz_j, _jz_k, _jz_l, _jz_m, _jz_n, _jz_oorder ;
    /* allocating memory if needed */
    if(_jz_maxOrderUsed < order )  { 
    	 if(_jz_ginitialized == 0) { 
    	   InitMyFloat(_jz_tvar1); InitMyFloat(_jz_tvar2);InitMyFloat(_jz_tvar3);InitMyFloat(_jz_tvar4);
    	   InitMyFloat(_jz_svar1); InitMyFloat(_jz_svar2);InitMyFloat(_jz_svar3);InitMyFloat(_jz_svar4);
    	   InitMyFloat(_jz_svar5); InitMyFloat(_jz_zvar1);InitMyFloat(_jz_zvar2);
    	   InitMyFloat(_jz_uvar1); InitMyFloat(_jz_uvar2);
    	   InitMyFloat(_jz_wvar3);InitMyFloat(_jz_wvar4);
    	   InitMyFloat(_jz_MyFloatZERO);
    	   MakeMyFloatC(_jz_MyFloatZERO, "0", (double)0);
    	   for(_jz_i=0; _jz_i<8; _jz_i++) {
    	       InitMyFloat(_jz_cvars[_jz_i]);
    	   }
    	 }
    	 if(rflag > 0) rflag = 0; /* have to recompute everything */
    	 _jz_oorder=_jz_maxOrderUsed;
    	 _jz_maxOrderUsed  = order;
    	 if(_jz_ginitialized) { 
    	   for(_jz_i=0; _jz_i< _jz_oorder+1; _jz_i++) {ClearMyFloat(_jz_oneOverN[_jz_i]); ClearMyFloat(_jz_theNs[_jz_i]);}    	   free(_jz_oneOverN); free(_jz_theNs);
    	 }
    	 _jz_theNs = (MY_FLOAT *)malloc((order+1) * sizeof(MY_FLOAT));
    	 _jz_oneOverN = (MY_FLOAT *)malloc((order+1) * sizeof(MY_FLOAT));
    	 for(_jz_i=0; _jz_i<order+1; _jz_i++) {InitMyFloat(_jz_oneOverN[_jz_i]);InitMyFloat(_jz_theNs[_jz_i]);}
    	 MakeMyFloatC(_jz_theNs[0],"0.0", (double)0.0);
    	 MakeMyFloatC(_jz_uvar1,"1.0", (double)1.0);
    	 for(_jz_i = 1; _jz_i <= order; _jz_i++) {
    		 AssignMyFloat(_jz_tvar2, _jz_theNs[_jz_i-1]);
    		 AddMyFloatA(_jz_theNs[_jz_i], _jz_tvar2, _jz_uvar1);
	}
    	 AssignMyFloat(_jz_oneOverN[0],_jz_uvar1);
    	 AssignMyFloat(_jz_oneOverN[1],_jz_uvar1);
    	 for(_jz_i = 2; _jz_i <= order; _jz_i++) {
    		 DivideMyFloatA(_jz_oneOverN[_jz_i], _jz_uvar1,_jz_theNs[_jz_i]);
	}
    	 if(_jz_ginitialized) {
    	    for(_jz_i=0; _jz_i<(_jz_oorder+1)*(114); _jz_i++) { ClearMyFloat(_jz_save[_jz_i]);} free(_jz_save);
    	 }
    	 _jz_save = (MY_FLOAT *)malloc((order+1)* 114 *sizeof(MY_FLOAT));
    	 for(_jz_i=0; _jz_i<(order+1)*(114); _jz_i++) { InitMyFloat(_jz_save[_jz_i]);}
    	 for(_jz_j = 0, _jz_k = 0; _jz_j < 114 ;  _jz_j++, _jz_k += order+1) { _jz_jet[_jz_j] =& (_jz_save[_jz_k]); }

    	 /* True constants, initialized only once. */
	 /* const: i_035=1 */
	 _jz_ivars[0]=1;
	 /* const: i_039=2 */
	 _jz_ivars[1]=2;
	 /* const: c_041=3. */
	 MakeMyFloatC(_jz_cvars[3],"3.",(double)3.);
	 /* negate: c_074=(-c_041) */
	 NegateMyFloatA(_jz_cvars[4],_jz_cvars[3]);
	 /* div: c_075=(c_074/i_039) */
	 DivideMyFloatA(_jz_cvars[5], _jz_cvars[4], MakeMyFloatB(_jz_uvar1,(double)_jz_ivars[1]));
	 /* const: i_044=3 */
	 _jz_ivars[2]=3;
	 /* negate: i_078=(-i_044) */
	 _jz_ivars[3]=-_jz_ivars[2];
    }

    if(rflag) {
    	 if(rflag < 0 ) return(NULL);
    	 for(_jz_i = 0; rflag != 0 && _jz_i < 20; _jz_i++) {
    		 if(MyFloatA_NEQ_B(_jz_jet[_jz_i][0], x[_jz_i])) rflag = 0;
    	 }
    }

    if(rflag == 0) {
	 /* initialize all constant vars and state variables */
	 _jz_lastOrder = 1;
	 AssignMyFloat(_jz_jet[0][0], x[0]);
	 AssignMyFloat(_jz_jet[1][0], x[1]);
	 AssignMyFloat(_jz_jet[2][0], x[2]);
	 AssignMyFloat(_jz_jet[3][0], x[3]);
	 AssignMyFloat(_jz_jet[4][0], x[4]);
	 AssignMyFloat(_jz_jet[5][0], x[5]);
	 AssignMyFloat(_jz_jet[6][0], x[6]);
	 AssignMyFloat(_jz_jet[7][0], x[7]);
	 AssignMyFloat(_jz_jet[8][0], x[8]);
	 AssignMyFloat(_jz_jet[9][0], x[9]);
	 AssignMyFloat(_jz_jet[10][0], x[10]);
	 AssignMyFloat(_jz_jet[11][0], x[11]);
	 AssignMyFloat(_jz_jet[12][0], x[12]);
	 AssignMyFloat(_jz_jet[13][0], x[13]);
	 AssignMyFloat(_jz_jet[14][0], x[14]);
	 AssignMyFloat(_jz_jet[15][0], x[15]);
	 AssignMyFloat(_jz_jet[16][0], x[16]);
	 AssignMyFloat(_jz_jet[17][0], x[17]);
	 AssignMyFloat(_jz_jet[18][0], x[18]);
	 AssignMyFloat(_jz_jet[19][0], x[19]);
	 /* plus: v_130=(v_015+v_016) */
	 AddMyFloatA(_jz_jet[20][0], _jz_jet[1][0], _jz_jet[2][0]);
	 /* minus: v_131=(v_017-v_014) */
	 SubstractMyFloatA(_jz_jet[21][0], _jz_jet[3][0], _jz_jet[0][0]);
	 /* minus: c_065=(i_035-mu) */
	 SubstractMyFloatA(_jz_cvars[0], MakeMyFloatB(_jz_tvar1,(double)_jz_ivars[0]), mu);
	 /* mult: c_069=(mu*mu) */
	 MultiplyMyFloatA(_jz_cvars[1], mu, mu);
	 /* mult: v_066=(v_014*v_014) */
	 MultiplyMyFloatA(_jz_jet[22][0], _jz_jet[0][0], _jz_jet[0][0]);
	 /* mult: v_067=(v_015*v_015) */
	 MultiplyMyFloatA(_jz_jet[23][0], _jz_jet[1][0], _jz_jet[1][0]);
	 /* plus: v_068=(v_066+v_067) */
	 AddMyFloatA(_jz_jet[24][0], _jz_jet[22][0], _jz_jet[23][0]);
	 /* mult: c_070=(i_039*mu) */
	 MultiplyMyFloatA(_jz_cvars[2], MakeMyFloatB(_jz_uvar1,(double)_jz_ivars[1]), mu);
	 /* mult: v_071=(c_070*v_014) */
	 MultiplyMyFloatA(_jz_jet[25][0], _jz_cvars[2], _jz_jet[0][0]);
	 /* minus: v_072=(v_068-v_071) */
	 SubstractMyFloatA(_jz_jet[26][0], _jz_jet[24][0], _jz_jet[25][0]);
	 /* plus: v_073=(c_069+v_072) */
	 AddMyFloatA(_jz_jet[27][0], _jz_cvars[1], _jz_jet[26][0]);
	 /* exponentiation: v_076=(v_073^c_075) */
		  /* integer exponent or half integer */
		 sqrtMyFloatA(_jz_svar1,_jz_jet[27][0]);
		 DivideMyFloatA(_jz_svar5,_jz_oneOverN[0],_jz_svar1);
		 { int n=3, m, mn=0; 
		   switch(n) {
			  case 0: AssignMyFloat(_jz_jet[28][0], _jz_oneOverN[0]); break;
			  case 1: AssignMyFloat(_jz_jet[28][0], _jz_svar5); break;
			  case 2: AssignMyFloat(_jz_svar1, _jz_svar5); MultiplyMyFloatA(_jz_jet[28][0],_jz_svar1,_jz_svar5); break;
			  case 3: AssignMyFloat(_jz_svar1, _jz_svar5); MultiplyMyFloatA(_jz_svar2,_jz_svar1,_jz_svar5);
			          MultiplyMyFloatA(_jz_jet[28][0],_jz_svar1,_jz_svar2); break;
			  default:
			   AssignMyFloat(_jz_svar1, _jz_oneOverN[0]); AssignMyFloat(_jz_svar2, _jz_svar5);
			     while(mn==0) {
			        m=n; n /=2; if(n+n != m) {
			           AssignMyFloat(_jz_svar3, _jz_svar1); MultiplyMyFloatA(_jz_svar1, _jz_svar3, _jz_svar2);
			           if(n==0){ mn=1;     AssignMyFloat(_jz_jet[28][0],_jz_svar1);}
			         }
			        if(mn==0) {AssignMyFloat(_jz_svar3, _jz_svar2);AssignMyFloat(_jz_svar4, _jz_svar2);
			                   MultiplyMyFloatA(_jz_svar2, _jz_svar3,_jz_svar4);}
			       }
			   break; 
			  }
		 } 
	 /* mult: v_077=(c_065*v_076) */
	 MultiplyMyFloatA(_jz_jet[29][0], _jz_cvars[0], _jz_jet[28][0]);
	 /* minus: v_081=(v_014-mu) */
	 SubstractMyFloatA(_jz_jet[30][0], _jz_jet[0][0], mu);
	 /* mult: v_133=(v_077*v_081) */
	 MultiplyMyFloatA(_jz_jet[31][0], _jz_jet[29][0], _jz_jet[30][0]);
	 /* minus: v_134=(v_017-v_133) */
	 SubstractMyFloatA(_jz_jet[32][0], _jz_jet[3][0], _jz_jet[31][0]);
	 /* mult: c_090=(c_065*c_065) */
	 MultiplyMyFloatA(_jz_cvars[6], _jz_cvars[0], _jz_cvars[0]);
	 /* mult: c_085=(c_065*i_039) */
	 MultiplyMyFloatA(_jz_cvars[7], _jz_cvars[0], MakeMyFloatB(_jz_tvar1,(double)_jz_ivars[1]));
	 /* mult: v_086=(c_085*v_014) */
	 MultiplyMyFloatA(_jz_jet[33][0], _jz_cvars[7], _jz_jet[0][0]);
	 /* plus: v_087=(v_068+v_086) */
	 AddMyFloatA(_jz_jet[34][0], _jz_jet[24][0], _jz_jet[33][0]);
	 /* plus: v_091=(c_090+v_087) */
	 AddMyFloatA(_jz_jet[35][0], _jz_cvars[6], _jz_jet[34][0]);
	 /* exponentiation: v_094=(v_091^c_075) */
		  /* integer exponent or half integer */
		 sqrtMyFloatA(_jz_svar1,_jz_jet[35][0]);
		 DivideMyFloatA(_jz_svar5,_jz_oneOverN[0],_jz_svar1);
		 { int n=3, m, mn=0; 
		   switch(n) {
			  case 0: AssignMyFloat(_jz_jet[36][0], _jz_oneOverN[0]); break;
			  case 1: AssignMyFloat(_jz_jet[36][0], _jz_svar5); break;
			  case 2: AssignMyFloat(_jz_svar1, _jz_svar5); MultiplyMyFloatA(_jz_jet[36][0],_jz_svar1,_jz_svar5); break;
			  case 3: AssignMyFloat(_jz_svar1, _jz_svar5); MultiplyMyFloatA(_jz_svar2,_jz_svar1,_jz_svar5);
			          MultiplyMyFloatA(_jz_jet[36][0],_jz_svar1,_jz_svar2); break;
			  default:
			   AssignMyFloat(_jz_svar1, _jz_oneOverN[0]); AssignMyFloat(_jz_svar2, _jz_svar5);
			     while(mn==0) {
			        m=n; n /=2; if(n+n != m) {
			           AssignMyFloat(_jz_svar3, _jz_svar1); MultiplyMyFloatA(_jz_svar1, _jz_svar3, _jz_svar2);
			           if(n==0){ mn=1;     AssignMyFloat(_jz_jet[36][0],_jz_svar1);}
			         }
			        if(mn==0) {AssignMyFloat(_jz_svar3, _jz_svar2);AssignMyFloat(_jz_svar4, _jz_svar2);
			                   MultiplyMyFloatA(_jz_svar2, _jz_svar3,_jz_svar4);}
			       }
			   break; 
			  }
		 } 
	 /* mult: v_095=(mu*v_094) */
	 MultiplyMyFloatA(_jz_jet[37][0], mu, _jz_jet[36][0]);
	 /* plus: v_099=(c_065+v_014) */
	 AddMyFloatA(_jz_jet[38][0], _jz_cvars[0], _jz_jet[0][0]);
	 /* mult: v_136=(v_095*v_099) */
	 MultiplyMyFloatA(_jz_jet[39][0], _jz_jet[37][0], _jz_jet[38][0]);
	 /* minus: v_137=(v_134-v_136) */
	 SubstractMyFloatA(_jz_jet[40][0], _jz_jet[32][0], _jz_jet[39][0]);
	 /* negate: v_138=(-v_016) */
	 NegateMyFloatA(_jz_jet[41][0],_jz_jet[2][0]);
	 /* plus: v_125=(v_077+v_095) */
	 AddMyFloatA(_jz_jet[42][0], _jz_jet[29][0], _jz_jet[37][0]);
	 /* mult: v_140=(v_015*v_125) */
	 MultiplyMyFloatA(_jz_jet[43][0], _jz_jet[1][0], _jz_jet[42][0]);
	 /* minus: v_141=(v_138-v_140) */
	 SubstractMyFloatA(_jz_jet[44][0], _jz_jet[41][0], _jz_jet[43][0]);
	 /* plus: v_142=(v_022+v_026) */
	 AddMyFloatA(_jz_jet[45][0], _jz_jet[8][0], _jz_jet[12][0]);
	 /* plus: v_143=(v_023+v_027) */
	 AddMyFloatA(_jz_jet[46][0], _jz_jet[9][0], _jz_jet[13][0]);
	 /* plus: v_144=(v_024+v_028) */
	 AddMyFloatA(_jz_jet[47][0], _jz_jet[10][0], _jz_jet[14][0]);
	 /* plus: v_145=(v_025+v_029) */
	 AddMyFloatA(_jz_jet[48][0], _jz_jet[11][0], _jz_jet[15][0]);
	 /* negate: v_146=(-v_018) */
	 NegateMyFloatA(_jz_jet[49][0],_jz_jet[4][0]);
	 /* plus: v_147=(v_030+v_146) */
	 AddMyFloatA(_jz_jet[50][0], _jz_jet[16][0], _jz_jet[49][0]);
	 /* negate: v_148=(-v_019) */
	 NegateMyFloatA(_jz_jet[51][0],_jz_jet[5][0]);
	 /* plus: v_149=(v_031+v_148) */
	 AddMyFloatA(_jz_jet[52][0], _jz_jet[17][0], _jz_jet[51][0]);
	 /* negate: v_150=(-v_020) */
	 NegateMyFloatA(_jz_jet[53][0],_jz_jet[6][0]);
	 /* plus: v_151=(v_032+v_150) */
	 AddMyFloatA(_jz_jet[54][0], _jz_jet[18][0], _jz_jet[53][0]);
	 /* negate: v_152=(-v_021) */
	 NegateMyFloatA(_jz_jet[55][0],_jz_jet[7][0]);
	 /* plus: v_153=(v_033+v_152) */
	 AddMyFloatA(_jz_jet[56][0], _jz_jet[19][0], _jz_jet[55][0]);
	 /* negate: v_102=(-v_077) */
	 NegateMyFloatA(_jz_jet[57][0],_jz_jet[29][0]);
	 /* mult: v_079=(i_078*v_077) */
	 MultiplyMyFloatA(_jz_jet[58][0], MakeMyFloatB(_jz_uvar1,(double)_jz_ivars[3]), _jz_jet[29][0]);
	 /* div: v_080=(v_079/v_073) */
	 DivideMyFloatA(_jz_jet[59][0], _jz_jet[58][0], _jz_jet[27][0]);
	 /* mult: v_082=(v_080*v_081) */
	 MultiplyMyFloatA(_jz_jet[60][0], _jz_jet[59][0], _jz_jet[30][0]);
	 /* mult: v_104=(v_081*v_082) */
	 MultiplyMyFloatA(_jz_jet[61][0], _jz_jet[30][0], _jz_jet[60][0]);
	 /* minus: v_105=(v_102-v_104) */
	 SubstractMyFloatA(_jz_jet[62][0], _jz_jet[57][0], _jz_jet[61][0]);
	 /* minus: v_106=(v_105-v_095) */
	 SubstractMyFloatA(_jz_jet[63][0], _jz_jet[62][0], _jz_jet[37][0]);
	 /* mult: v_097=(i_078*v_095) */
	 MultiplyMyFloatA(_jz_jet[64][0], MakeMyFloatB(_jz_tvar1,(double)_jz_ivars[3]), _jz_jet[37][0]);
	 /* div: v_098=(v_097/v_091) */
	 DivideMyFloatA(_jz_jet[65][0], _jz_jet[64][0], _jz_jet[35][0]);
	 /* mult: v_100=(v_098*v_099) */
	 MultiplyMyFloatA(_jz_jet[66][0], _jz_jet[65][0], _jz_jet[38][0]);
	 /* mult: v_108=(v_099*v_100) */
	 MultiplyMyFloatA(_jz_jet[67][0], _jz_jet[38][0], _jz_jet[66][0]);
	 /* minus: v_109=(v_106-v_108) */
	 SubstractMyFloatA(_jz_jet[68][0], _jz_jet[63][0], _jz_jet[67][0]);
	 /* mult: v_154=(v_018*v_109) */
	 MultiplyMyFloatA(_jz_jet[69][0], _jz_jet[4][0], _jz_jet[68][0]);
	 /* mult: v_083=(v_015*v_080) */
	 MultiplyMyFloatA(_jz_jet[70][0], _jz_jet[1][0], _jz_jet[59][0]);
	 /* negate: v_111=(-v_081) */
	 NegateMyFloatA(_jz_jet[71][0],_jz_jet[30][0]);
	 /* mult: v_112=(v_083*v_111) */
	 MultiplyMyFloatA(_jz_jet[72][0], _jz_jet[70][0], _jz_jet[71][0]);
	 /* mult: v_101=(v_015*v_098) */
	 MultiplyMyFloatA(_jz_jet[73][0], _jz_jet[1][0], _jz_jet[65][0]);
	 /* mult: v_114=(v_099*v_101) */
	 MultiplyMyFloatA(_jz_jet[74][0], _jz_jet[38][0], _jz_jet[73][0]);
	 /* minus: v_115=(v_112-v_114) */
	 SubstractMyFloatA(_jz_jet[75][0], _jz_jet[72][0], _jz_jet[74][0]);
	 /* mult: v_155=(v_022*v_115) */
	 MultiplyMyFloatA(_jz_jet[76][0], _jz_jet[8][0], _jz_jet[75][0]);
	 /* plus: v_156=(v_154+v_155) */
	 AddMyFloatA(_jz_jet[77][0], _jz_jet[69][0], _jz_jet[76][0]);
	 /* plus: v_157=(v_030+v_156) */
	 AddMyFloatA(_jz_jet[78][0], _jz_jet[16][0], _jz_jet[77][0]);
	 /* mult: v_158=(v_019*v_109) */
	 MultiplyMyFloatA(_jz_jet[79][0], _jz_jet[5][0], _jz_jet[68][0]);
	 /* mult: v_159=(v_023*v_115) */
	 MultiplyMyFloatA(_jz_jet[80][0], _jz_jet[9][0], _jz_jet[75][0]);
	 /* plus: v_160=(v_158+v_159) */
	 AddMyFloatA(_jz_jet[81][0], _jz_jet[79][0], _jz_jet[80][0]);
	 /* plus: v_161=(v_031+v_160) */
	 AddMyFloatA(_jz_jet[82][0], _jz_jet[17][0], _jz_jet[81][0]);
	 /* mult: v_162=(v_020*v_109) */
	 MultiplyMyFloatA(_jz_jet[83][0], _jz_jet[6][0], _jz_jet[68][0]);
	 /* mult: v_163=(v_024*v_115) */
	 MultiplyMyFloatA(_jz_jet[84][0], _jz_jet[10][0], _jz_jet[75][0]);
	 /* plus: v_164=(v_162+v_163) */
	 AddMyFloatA(_jz_jet[85][0], _jz_jet[83][0], _jz_jet[84][0]);
	 /* plus: v_165=(v_032+v_164) */
	 AddMyFloatA(_jz_jet[86][0], _jz_jet[18][0], _jz_jet[85][0]);
	 /* mult: v_166=(v_021*v_109) */
	 MultiplyMyFloatA(_jz_jet[87][0], _jz_jet[7][0], _jz_jet[68][0]);
	 /* mult: v_167=(v_025*v_115) */
	 MultiplyMyFloatA(_jz_jet[88][0], _jz_jet[11][0], _jz_jet[75][0]);
	 /* plus: v_168=(v_166+v_167) */
	 AddMyFloatA(_jz_jet[89][0], _jz_jet[87][0], _jz_jet[88][0]);
	 /* plus: v_169=(v_033+v_168) */
	 AddMyFloatA(_jz_jet[90][0], _jz_jet[19][0], _jz_jet[89][0]);
	 /* negate: v_122=(-v_015) */
	 NegateMyFloatA(_jz_jet[91][0],_jz_jet[1][0]);
	 /* plus: v_123=(v_082+v_100) */
	 AddMyFloatA(_jz_jet[92][0], _jz_jet[60][0], _jz_jet[66][0]);
	 /* mult: v_124=(v_122*v_123) */
	 MultiplyMyFloatA(_jz_jet[93][0], _jz_jet[91][0], _jz_jet[92][0]);
	 /* mult: v_170=(v_018*v_124) */
	 MultiplyMyFloatA(_jz_jet[94][0], _jz_jet[4][0], _jz_jet[93][0]);
	 /* negate: v_126=(-v_125) */
	 NegateMyFloatA(_jz_jet[95][0],_jz_jet[42][0]);
	 /* plus: v_127=(v_083+v_101) */
	 AddMyFloatA(_jz_jet[96][0], _jz_jet[70][0], _jz_jet[73][0]);
	 /* mult: v_128=(v_015*v_127) */
	 MultiplyMyFloatA(_jz_jet[97][0], _jz_jet[1][0], _jz_jet[96][0]);
	 /* minus: v_129=(v_126-v_128) */
	 SubstractMyFloatA(_jz_jet[98][0], _jz_jet[95][0], _jz_jet[97][0]);
	 /* mult: v_171=(v_022*v_129) */
	 MultiplyMyFloatA(_jz_jet[99][0], _jz_jet[8][0], _jz_jet[98][0]);
	 /* plus: v_172=(v_170+v_171) */
	 AddMyFloatA(_jz_jet[100][0], _jz_jet[94][0], _jz_jet[99][0]);
	 /* minus: v_173=(v_172-v_026) */
	 SubstractMyFloatA(_jz_jet[101][0], _jz_jet[100][0], _jz_jet[12][0]);
	 /* mult: v_174=(v_019*v_124) */
	 MultiplyMyFloatA(_jz_jet[102][0], _jz_jet[5][0], _jz_jet[93][0]);
	 /* mult: v_175=(v_023*v_129) */
	 MultiplyMyFloatA(_jz_jet[103][0], _jz_jet[9][0], _jz_jet[98][0]);
	 /* plus: v_176=(v_174+v_175) */
	 AddMyFloatA(_jz_jet[104][0], _jz_jet[102][0], _jz_jet[103][0]);
	 /* minus: v_177=(v_176-v_027) */
	 SubstractMyFloatA(_jz_jet[105][0], _jz_jet[104][0], _jz_jet[13][0]);
	 /* mult: v_178=(v_020*v_124) */
	 MultiplyMyFloatA(_jz_jet[106][0], _jz_jet[6][0], _jz_jet[93][0]);
	 /* mult: v_179=(v_024*v_129) */
	 MultiplyMyFloatA(_jz_jet[107][0], _jz_jet[10][0], _jz_jet[98][0]);
	 /* plus: v_180=(v_178+v_179) */
	 AddMyFloatA(_jz_jet[108][0], _jz_jet[106][0], _jz_jet[107][0]);
	 /* minus: v_181=(v_180-v_028) */
	 SubstractMyFloatA(_jz_jet[109][0], _jz_jet[108][0], _jz_jet[14][0]);
	 /* mult: v_182=(v_021*v_124) */
	 MultiplyMyFloatA(_jz_jet[110][0], _jz_jet[7][0], _jz_jet[93][0]);
	 /* mult: v_183=(v_025*v_129) */
	 MultiplyMyFloatA(_jz_jet[111][0], _jz_jet[11][0], _jz_jet[98][0]);
	 /* plus: v_184=(v_182+v_183) */
	 AddMyFloatA(_jz_jet[112][0], _jz_jet[110][0], _jz_jet[111][0]);
	 /* minus: v_185=(v_184-v_029) */
	 SubstractMyFloatA(_jz_jet[113][0], _jz_jet[112][0], _jz_jet[15][0]);

	 /* the first derivative of state variables */
	 /* state variable 0: */
	 AssignMyFloat(_jz_jet[0][1], _jz_jet[20][0]);
	 /* state variable 1: */
	 AssignMyFloat(_jz_jet[1][1], _jz_jet[21][0]);
	 /* state variable 2: */
	 AssignMyFloat(_jz_jet[2][1], _jz_jet[40][0]);
	 /* state variable 3: */
	 AssignMyFloat(_jz_jet[3][1], _jz_jet[44][0]);
	 /* state variable 4: */
	 AssignMyFloat(_jz_jet[4][1], _jz_jet[45][0]);
	 /* state variable 5: */
	 AssignMyFloat(_jz_jet[5][1], _jz_jet[46][0]);
	 /* state variable 6: */
	 AssignMyFloat(_jz_jet[6][1], _jz_jet[47][0]);
	 /* state variable 7: */
	 AssignMyFloat(_jz_jet[7][1], _jz_jet[48][0]);
	 /* state variable 8: */
	 AssignMyFloat(_jz_jet[8][1], _jz_jet[50][0]);
	 /* state variable 9: */
	 AssignMyFloat(_jz_jet[9][1], _jz_jet[52][0]);
	 /* state variable 10: */
	 AssignMyFloat(_jz_jet[10][1], _jz_jet[54][0]);
	 /* state variable 11: */
	 AssignMyFloat(_jz_jet[11][1], _jz_jet[56][0]);
	 /* state variable 12: */
	 AssignMyFloat(_jz_jet[12][1], _jz_jet[78][0]);
	 /* state variable 13: */
	 AssignMyFloat(_jz_jet[13][1], _jz_jet[82][0]);
	 /* state variable 14: */
	 AssignMyFloat(_jz_jet[14][1], _jz_jet[86][0]);
	 /* state variable 15: */
	 AssignMyFloat(_jz_jet[15][1], _jz_jet[90][0]);
	 /* state variable 16: */
	 AssignMyFloat(_jz_jet[16][1], _jz_jet[101][0]);
	 /* state variable 17: */
	 AssignMyFloat(_jz_jet[17][1], _jz_jet[105][0]);
	 /* state variable 18: */
	 AssignMyFloat(_jz_jet[18][1], _jz_jet[109][0]);
	 /* state variable 19: */
	 AssignMyFloat(_jz_jet[19][1], _jz_jet[113][0]);
	}

	 /* compute the kth order derivatives of all vars */
	 for(_jz_k = _jz_lastOrder; _jz_k < order; _jz_k++) {
		 /* derivative for tmp variables */
		 /* plus: v_130=(v_015+v_016) */
		 AddMyFloatA(_jz_jet[20][_jz_k], _jz_jet[1][_jz_k],_jz_jet[2][_jz_k]);
		 /* minus: v_131=(v_017-v_014) */
		 SubstractMyFloatA(_jz_jet[21][_jz_k], _jz_jet[3][_jz_k],_jz_jet[0][_jz_k]);
		 /* mult: v_066=(v_014*v_014) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 int parity=(_jz_k&1), half=(_jz_k+1)>>1;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<half; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[0][_jz_l], _jz_jet[0][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(tmp2, tmp);
			 AddMyFloatA(tmp1, tmp2, tmp);
			 if(parity==0) {
			     MultiplyMyFloatA(tmp2, _jz_jet[0][half], _jz_jet[0][half]);
			     AddMyFloatA(_jz_jet[22][_jz_k], tmp2, tmp1);
			 } else {
			     AssignMyFloat(_jz_jet[22][_jz_k], tmp1);
			 }
		 }
		 /* mult: v_067=(v_015*v_015) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 int parity=(_jz_k&1), half=(_jz_k+1)>>1;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<half; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[1][_jz_l], _jz_jet[1][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(tmp2, tmp);
			 AddMyFloatA(tmp1, tmp2, tmp);
			 if(parity==0) {
			     MultiplyMyFloatA(tmp2, _jz_jet[1][half], _jz_jet[1][half]);
			     AddMyFloatA(_jz_jet[23][_jz_k], tmp2, tmp1);
			 } else {
			     AssignMyFloat(_jz_jet[23][_jz_k], tmp1);
			 }
		 }
		 /* plus: v_068=(v_066+v_067) */
		 AddMyFloatA(_jz_jet[24][_jz_k], _jz_jet[22][_jz_k],_jz_jet[23][_jz_k]);
		 /* mult: v_071=(c_070*v_014) */
		 MultiplyMyFloatA(_jz_jet[25][_jz_k], _jz_cvars[2], _jz_jet[0][_jz_k]);
		 /* minus: v_072=(v_068-v_071) */
		 SubstractMyFloatA(_jz_jet[26][_jz_k], _jz_jet[24][_jz_k],_jz_jet[25][_jz_k]);
		 /* plus: v_073=(c_069+v_072) */
		 AssignMyFloat(_jz_jet[27][_jz_k], _jz_jet[26][_jz_k]);
		 /* exponentiation: v_076=(v_073^c_075) */
		 { /* exponentiation */
				 /* expr^(-3/2)/ */ 
			 int  ppk=(-3)*_jz_k, qqk=(2)*_jz_k, pq=-1;
			 static MY_FLOAT tmp1, tmp2, tmp3, tmpC, tmp;
			 if(_jz_initialized==0) {
			  InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp3);
			  InitMyFloat(tmpC);InitMyFloat(tmp);
			 }
			 AssignMyFloat(tmp,  _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<_jz_k; _jz_l++) {
			     MakeMyFloatA(tmpC, ppk);
			     ppk -= pq  ;
			     MultiplyMyFloatA(tmp1, _jz_jet[28][_jz_l],_jz_jet[27][_jz_k-_jz_l]);
			     MultiplyMyFloatA(tmp2, tmpC, tmp1);
			     AddMyFloatA(tmp1,  tmp, tmp2);
			     AssignMyFloat(tmp,  tmp1);
			 }
			 MakeMyFloatA(tmp3,qqk);
			 MultiplyMyFloatA(tmp1, _jz_jet[27][0], tmp3);
			 DivideMyFloatA(_jz_jet[28][_jz_k], tmp, tmp1);
		}
		 /* mult: v_077=(c_065*v_076) */
		 MultiplyMyFloatA(_jz_jet[29][_jz_k], _jz_cvars[0], _jz_jet[28][_jz_k]);
		 /* minus: v_081=(v_014-mu) */
		 AssignMyFloat(_jz_jet[30][_jz_k], _jz_jet[0][_jz_k]);
		 /* mult: v_133=(v_077*v_081) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[29][_jz_l], _jz_jet[30][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[31][_jz_k], tmp);
		 }
		 /* minus: v_134=(v_017-v_133) */
		 SubstractMyFloatA(_jz_jet[32][_jz_k], _jz_jet[3][_jz_k],_jz_jet[31][_jz_k]);
		 /* mult: v_086=(c_085*v_014) */
		 MultiplyMyFloatA(_jz_jet[33][_jz_k], _jz_cvars[7], _jz_jet[0][_jz_k]);
		 /* plus: v_087=(v_068+v_086) */
		 AddMyFloatA(_jz_jet[34][_jz_k], _jz_jet[24][_jz_k],_jz_jet[33][_jz_k]);
		 /* plus: v_091=(c_090+v_087) */
		 AssignMyFloat(_jz_jet[35][_jz_k], _jz_jet[34][_jz_k]);
		 /* exponentiation: v_094=(v_091^c_075) */
		 { /* exponentiation */
				 /* expr^(-3/2)/ */ 
			 int  ppk=(-3)*_jz_k, qqk=(2)*_jz_k, pq=-1;
			 static MY_FLOAT tmp1, tmp2, tmp3, tmpC, tmp;
			 if(_jz_initialized==0) {
			  InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp3);
			  InitMyFloat(tmpC);InitMyFloat(tmp);
			 }
			 AssignMyFloat(tmp,  _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<_jz_k; _jz_l++) {
			     MakeMyFloatA(tmpC, ppk);
			     ppk -= pq  ;
			     MultiplyMyFloatA(tmp1, _jz_jet[36][_jz_l],_jz_jet[35][_jz_k-_jz_l]);
			     MultiplyMyFloatA(tmp2, tmpC, tmp1);
			     AddMyFloatA(tmp1,  tmp, tmp2);
			     AssignMyFloat(tmp,  tmp1);
			 }
			 MakeMyFloatA(tmp3,qqk);
			 MultiplyMyFloatA(tmp1, _jz_jet[35][0], tmp3);
			 DivideMyFloatA(_jz_jet[36][_jz_k], tmp, tmp1);
		}
		 /* mult: v_095=(mu*v_094) */
		 MultiplyMyFloatA(_jz_jet[37][_jz_k], mu, _jz_jet[36][_jz_k]);
		 /* plus: v_099=(c_065+v_014) */
		 AssignMyFloat(_jz_jet[38][_jz_k], _jz_jet[0][_jz_k]);
		 /* mult: v_136=(v_095*v_099) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[37][_jz_l], _jz_jet[38][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[39][_jz_k], tmp);
		 }
		 /* minus: v_137=(v_134-v_136) */
		 SubstractMyFloatA(_jz_jet[40][_jz_k], _jz_jet[32][_jz_k],_jz_jet[39][_jz_k]);
		 /* negation: v_138=(-v_016) */
		 NegateMyFloatA(_jz_jet[41][_jz_k], _jz_jet[2][_jz_k]);
		 /* plus: v_125=(v_077+v_095) */
		 AddMyFloatA(_jz_jet[42][_jz_k], _jz_jet[29][_jz_k],_jz_jet[37][_jz_k]);
		 /* mult: v_140=(v_015*v_125) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[1][_jz_l], _jz_jet[42][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[43][_jz_k], tmp);
		 }
		 /* minus: v_141=(v_138-v_140) */
		 SubstractMyFloatA(_jz_jet[44][_jz_k], _jz_jet[41][_jz_k],_jz_jet[43][_jz_k]);
		 /* plus: v_142=(v_022+v_026) */
		 AddMyFloatA(_jz_jet[45][_jz_k], _jz_jet[8][_jz_k],_jz_jet[12][_jz_k]);
		 /* plus: v_143=(v_023+v_027) */
		 AddMyFloatA(_jz_jet[46][_jz_k], _jz_jet[9][_jz_k],_jz_jet[13][_jz_k]);
		 /* plus: v_144=(v_024+v_028) */
		 AddMyFloatA(_jz_jet[47][_jz_k], _jz_jet[10][_jz_k],_jz_jet[14][_jz_k]);
		 /* plus: v_145=(v_025+v_029) */
		 AddMyFloatA(_jz_jet[48][_jz_k], _jz_jet[11][_jz_k],_jz_jet[15][_jz_k]);
		 /* negation: v_146=(-v_018) */
		 NegateMyFloatA(_jz_jet[49][_jz_k], _jz_jet[4][_jz_k]);
		 /* plus: v_147=(v_030+v_146) */
		 AddMyFloatA(_jz_jet[50][_jz_k], _jz_jet[16][_jz_k],_jz_jet[49][_jz_k]);
		 /* negation: v_148=(-v_019) */
		 NegateMyFloatA(_jz_jet[51][_jz_k], _jz_jet[5][_jz_k]);
		 /* plus: v_149=(v_031+v_148) */
		 AddMyFloatA(_jz_jet[52][_jz_k], _jz_jet[17][_jz_k],_jz_jet[51][_jz_k]);
		 /* negation: v_150=(-v_020) */
		 NegateMyFloatA(_jz_jet[53][_jz_k], _jz_jet[6][_jz_k]);
		 /* plus: v_151=(v_032+v_150) */
		 AddMyFloatA(_jz_jet[54][_jz_k], _jz_jet[18][_jz_k],_jz_jet[53][_jz_k]);
		 /* negation: v_152=(-v_021) */
		 NegateMyFloatA(_jz_jet[55][_jz_k], _jz_jet[7][_jz_k]);
		 /* plus: v_153=(v_033+v_152) */
		 AddMyFloatA(_jz_jet[56][_jz_k], _jz_jet[19][_jz_k],_jz_jet[55][_jz_k]);
		 /* negation: v_102=(-v_077) */
		 NegateMyFloatA(_jz_jet[57][_jz_k], _jz_jet[29][_jz_k]);
		 /* mult: v_079=(i_078*v_077) */
		 MultiplyMyFloatA(_jz_jet[58][_jz_k], MakeMyFloatB(_jz_uvar1,(double)_jz_ivars[3]), _jz_jet[29][_jz_k]);
		 /* div: v_080=(v_079/v_073) */
		 { /* division */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=1; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[27][_jz_l],_jz_jet[59][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			     AssignMyFloat(tmp2, tmp);
			 SubstractMyFloatA(tmp, _jz_jet[58][_jz_k], tmp2);
			 DivideMyFloatA(_jz_jet[59][_jz_k], tmp, _jz_jet[27][0]);
		 }
		 /* mult: v_082=(v_080*v_081) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[59][_jz_l], _jz_jet[30][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[60][_jz_k], tmp);
		 }
		 /* mult: v_104=(v_081*v_082) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[30][_jz_l], _jz_jet[60][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[61][_jz_k], tmp);
		 }
		 /* minus: v_105=(v_102-v_104) */
		 SubstractMyFloatA(_jz_jet[62][_jz_k], _jz_jet[57][_jz_k],_jz_jet[61][_jz_k]);
		 /* minus: v_106=(v_105-v_095) */
		 SubstractMyFloatA(_jz_jet[63][_jz_k], _jz_jet[62][_jz_k],_jz_jet[37][_jz_k]);
		 /* mult: v_097=(i_078*v_095) */
		 MultiplyMyFloatA(_jz_jet[64][_jz_k], MakeMyFloatB(_jz_tvar1,(double)_jz_ivars[3]), _jz_jet[37][_jz_k]);
		 /* div: v_098=(v_097/v_091) */
		 { /* division */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=1; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[35][_jz_l],_jz_jet[65][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			     AssignMyFloat(tmp2, tmp);
			 SubstractMyFloatA(tmp, _jz_jet[64][_jz_k], tmp2);
			 DivideMyFloatA(_jz_jet[65][_jz_k], tmp, _jz_jet[35][0]);
		 }
		 /* mult: v_100=(v_098*v_099) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[65][_jz_l], _jz_jet[38][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[66][_jz_k], tmp);
		 }
		 /* mult: v_108=(v_099*v_100) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[38][_jz_l], _jz_jet[66][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[67][_jz_k], tmp);
		 }
		 /* minus: v_109=(v_106-v_108) */
		 SubstractMyFloatA(_jz_jet[68][_jz_k], _jz_jet[63][_jz_k],_jz_jet[67][_jz_k]);
		 /* mult: v_154=(v_018*v_109) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[4][_jz_l], _jz_jet[68][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[69][_jz_k], tmp);
		 }
		 /* mult: v_083=(v_015*v_080) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[1][_jz_l], _jz_jet[59][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[70][_jz_k], tmp);
		 }
		 /* negation: v_111=(-v_081) */
		 NegateMyFloatA(_jz_jet[71][_jz_k], _jz_jet[30][_jz_k]);
		 /* mult: v_112=(v_083*v_111) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[70][_jz_l], _jz_jet[71][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[72][_jz_k], tmp);
		 }
		 /* mult: v_101=(v_015*v_098) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[1][_jz_l], _jz_jet[65][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[73][_jz_k], tmp);
		 }
		 /* mult: v_114=(v_099*v_101) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[38][_jz_l], _jz_jet[73][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[74][_jz_k], tmp);
		 }
		 /* minus: v_115=(v_112-v_114) */
		 SubstractMyFloatA(_jz_jet[75][_jz_k], _jz_jet[72][_jz_k],_jz_jet[74][_jz_k]);
		 /* mult: v_155=(v_022*v_115) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[8][_jz_l], _jz_jet[75][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[76][_jz_k], tmp);
		 }
		 /* plus: v_156=(v_154+v_155) */
		 AddMyFloatA(_jz_jet[77][_jz_k], _jz_jet[69][_jz_k],_jz_jet[76][_jz_k]);
		 /* plus: v_157=(v_030+v_156) */
		 AddMyFloatA(_jz_jet[78][_jz_k], _jz_jet[16][_jz_k],_jz_jet[77][_jz_k]);
		 /* mult: v_158=(v_019*v_109) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[5][_jz_l], _jz_jet[68][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[79][_jz_k], tmp);
		 }
		 /* mult: v_159=(v_023*v_115) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[9][_jz_l], _jz_jet[75][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[80][_jz_k], tmp);
		 }
		 /* plus: v_160=(v_158+v_159) */
		 AddMyFloatA(_jz_jet[81][_jz_k], _jz_jet[79][_jz_k],_jz_jet[80][_jz_k]);
		 /* plus: v_161=(v_031+v_160) */
		 AddMyFloatA(_jz_jet[82][_jz_k], _jz_jet[17][_jz_k],_jz_jet[81][_jz_k]);
		 /* mult: v_162=(v_020*v_109) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[6][_jz_l], _jz_jet[68][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[83][_jz_k], tmp);
		 }
		 /* mult: v_163=(v_024*v_115) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[10][_jz_l], _jz_jet[75][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[84][_jz_k], tmp);
		 }
		 /* plus: v_164=(v_162+v_163) */
		 AddMyFloatA(_jz_jet[85][_jz_k], _jz_jet[83][_jz_k],_jz_jet[84][_jz_k]);
		 /* plus: v_165=(v_032+v_164) */
		 AddMyFloatA(_jz_jet[86][_jz_k], _jz_jet[18][_jz_k],_jz_jet[85][_jz_k]);
		 /* mult: v_166=(v_021*v_109) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[7][_jz_l], _jz_jet[68][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[87][_jz_k], tmp);
		 }
		 /* mult: v_167=(v_025*v_115) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[11][_jz_l], _jz_jet[75][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[88][_jz_k], tmp);
		 }
		 /* plus: v_168=(v_166+v_167) */
		 AddMyFloatA(_jz_jet[89][_jz_k], _jz_jet[87][_jz_k],_jz_jet[88][_jz_k]);
		 /* plus: v_169=(v_033+v_168) */
		 AddMyFloatA(_jz_jet[90][_jz_k], _jz_jet[19][_jz_k],_jz_jet[89][_jz_k]);
		 /* negation: v_122=(-v_015) */
		 NegateMyFloatA(_jz_jet[91][_jz_k], _jz_jet[1][_jz_k]);
		 /* plus: v_123=(v_082+v_100) */
		 AddMyFloatA(_jz_jet[92][_jz_k], _jz_jet[60][_jz_k],_jz_jet[66][_jz_k]);
		 /* mult: v_124=(v_122*v_123) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[91][_jz_l], _jz_jet[92][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[93][_jz_k], tmp);
		 }
		 /* mult: v_170=(v_018*v_124) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[4][_jz_l], _jz_jet[93][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[94][_jz_k], tmp);
		 }
		 /* negation: v_126=(-v_125) */
		 NegateMyFloatA(_jz_jet[95][_jz_k], _jz_jet[42][_jz_k]);
		 /* plus: v_127=(v_083+v_101) */
		 AddMyFloatA(_jz_jet[96][_jz_k], _jz_jet[70][_jz_k],_jz_jet[73][_jz_k]);
		 /* mult: v_128=(v_015*v_127) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[1][_jz_l], _jz_jet[96][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[97][_jz_k], tmp);
		 }
		 /* minus: v_129=(v_126-v_128) */
		 SubstractMyFloatA(_jz_jet[98][_jz_k], _jz_jet[95][_jz_k],_jz_jet[97][_jz_k]);
		 /* mult: v_171=(v_022*v_129) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[8][_jz_l], _jz_jet[98][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[99][_jz_k], tmp);
		 }
		 /* plus: v_172=(v_170+v_171) */
		 AddMyFloatA(_jz_jet[100][_jz_k], _jz_jet[94][_jz_k],_jz_jet[99][_jz_k]);
		 /* minus: v_173=(v_172-v_026) */
		 SubstractMyFloatA(_jz_jet[101][_jz_k], _jz_jet[100][_jz_k],_jz_jet[12][_jz_k]);
		 /* mult: v_174=(v_019*v_124) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[5][_jz_l], _jz_jet[93][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[102][_jz_k], tmp);
		 }
		 /* mult: v_175=(v_023*v_129) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[9][_jz_l], _jz_jet[98][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[103][_jz_k], tmp);
		 }
		 /* plus: v_176=(v_174+v_175) */
		 AddMyFloatA(_jz_jet[104][_jz_k], _jz_jet[102][_jz_k],_jz_jet[103][_jz_k]);
		 /* minus: v_177=(v_176-v_027) */
		 SubstractMyFloatA(_jz_jet[105][_jz_k], _jz_jet[104][_jz_k],_jz_jet[13][_jz_k]);
		 /* mult: v_178=(v_020*v_124) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[6][_jz_l], _jz_jet[93][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[106][_jz_k], tmp);
		 }
		 /* mult: v_179=(v_024*v_129) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[10][_jz_l], _jz_jet[98][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[107][_jz_k], tmp);
		 }
		 /* plus: v_180=(v_178+v_179) */
		 AddMyFloatA(_jz_jet[108][_jz_k], _jz_jet[106][_jz_k],_jz_jet[107][_jz_k]);
		 /* minus: v_181=(v_180-v_028) */
		 SubstractMyFloatA(_jz_jet[109][_jz_k], _jz_jet[108][_jz_k],_jz_jet[14][_jz_k]);
		 /* mult: v_182=(v_021*v_124) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[7][_jz_l], _jz_jet[93][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[110][_jz_k], tmp);
		 }
		 /* mult: v_183=(v_025*v_129) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 if(_jz_initialized==0) { InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);}
			 AssignMyFloat(tmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyMyFloatA(tmp1, _jz_jet[11][_jz_l], _jz_jet[98][_jz_k-_jz_l]);
			     AssignMyFloat(tmp2, tmp);
			     AddMyFloatA(tmp, tmp2, tmp1);
			 }
			 AssignMyFloat(_jz_jet[111][_jz_k], tmp);
		 }
		 /* plus: v_184=(v_182+v_183) */
		 AddMyFloatA(_jz_jet[112][_jz_k], _jz_jet[110][_jz_k],_jz_jet[111][_jz_k]);
		 /* minus: v_185=(v_184-v_029) */
		 SubstractMyFloatA(_jz_jet[113][_jz_k], _jz_jet[112][_jz_k],_jz_jet[15][_jz_k]);
		 /* derivative of state variables */
		 _jz_m = _jz_k+1;
		 /* state variable 0: */
		 DivideMyFloatByInt(_jz_jet[0][_jz_m], _jz_jet[20][_jz_k], _jz_m);
		 /* state variable 1: */
		 DivideMyFloatByInt(_jz_jet[1][_jz_m], _jz_jet[21][_jz_k], _jz_m);
		 /* state variable 2: */
		 DivideMyFloatByInt(_jz_jet[2][_jz_m], _jz_jet[40][_jz_k], _jz_m);
		 /* state variable 3: */
		 DivideMyFloatByInt(_jz_jet[3][_jz_m], _jz_jet[44][_jz_k], _jz_m);
		 /* state variable 4: */
		 DivideMyFloatByInt(_jz_jet[4][_jz_m], _jz_jet[45][_jz_k], _jz_m);
		 /* state variable 5: */
		 DivideMyFloatByInt(_jz_jet[5][_jz_m], _jz_jet[46][_jz_k], _jz_m);
		 /* state variable 6: */
		 DivideMyFloatByInt(_jz_jet[6][_jz_m], _jz_jet[47][_jz_k], _jz_m);
		 /* state variable 7: */
		 DivideMyFloatByInt(_jz_jet[7][_jz_m], _jz_jet[48][_jz_k], _jz_m);
		 /* state variable 8: */
		 DivideMyFloatByInt(_jz_jet[8][_jz_m], _jz_jet[50][_jz_k], _jz_m);
		 /* state variable 9: */
		 DivideMyFloatByInt(_jz_jet[9][_jz_m], _jz_jet[52][_jz_k], _jz_m);
		 /* state variable 10: */
		 DivideMyFloatByInt(_jz_jet[10][_jz_m], _jz_jet[54][_jz_k], _jz_m);
		 /* state variable 11: */
		 DivideMyFloatByInt(_jz_jet[11][_jz_m], _jz_jet[56][_jz_k], _jz_m);
		 /* state variable 12: */
		 DivideMyFloatByInt(_jz_jet[12][_jz_m], _jz_jet[78][_jz_k], _jz_m);
		 /* state variable 13: */
		 DivideMyFloatByInt(_jz_jet[13][_jz_m], _jz_jet[82][_jz_k], _jz_m);
		 /* state variable 14: */
		 DivideMyFloatByInt(_jz_jet[14][_jz_m], _jz_jet[86][_jz_k], _jz_m);
		 /* state variable 15: */
		 DivideMyFloatByInt(_jz_jet[15][_jz_m], _jz_jet[90][_jz_k], _jz_m);
		 /* state variable 16: */
		 DivideMyFloatByInt(_jz_jet[16][_jz_m], _jz_jet[101][_jz_k], _jz_m);
		 /* state variable 17: */
		 DivideMyFloatByInt(_jz_jet[17][_jz_m], _jz_jet[105][_jz_k], _jz_m);
		 /* state variable 18: */
		 DivideMyFloatByInt(_jz_jet[18][_jz_m], _jz_jet[109][_jz_k], _jz_m);
		 /* state variable 19: */
		 DivideMyFloatByInt(_jz_jet[19][_jz_m], _jz_jet[113][_jz_k], _jz_m);
		 _jz_initialized=1;
	 }
    _jz_lastOrder = order;
    _jz_ginitialized=1;
    return(_jz_jet);
}
MY_FLOAT **taylor_coefficients_rtbp2dv(MY_FLOAT t, MY_FLOAT *x, int order)
{
    return(taylor_coefficients_rtbp2dvA(t,x,order,0));
}

/******************** Translation Info *****************************/
/*


===================================================================================
=======                                                                      ======
=======                         Final Variable List                          ======
	    (114 + 0) vars, (8 + 0) cvars and (4 + 0) ivars 
=======                                                                      ======
===================================================================================
	v_014 (state variable)
	v_015 (state variable)
	v_016 (state variable)
	v_017 (state variable)
	v_018 (state variable)
	v_019 (state variable)
	v_020 (state variable)
	v_021 (state variable)
	v_022 (state variable)
	v_023 (state variable)
	v_024 (state variable)
	v_025 (state variable)
	v_026 (state variable)
	v_027 (state variable)
	v_028 (state variable)
	v_029 (state variable)
	v_030 (state variable)
	v_031 (state variable)
	v_032 (state variable)
	v_033 (state variable)
	v_130 = (v_015+v_016)                            (20 0)
	v_131 = (v_017-v_014)                            (21 0)
	i_035 = 1                                        (0 0) (a number)
	c_065 = (i_035-mu)                               (0 0)
	c_069 = (mu*mu)                                  (1 0)
	v_066 = (v_014*v_014)                            (22 0)
	v_067 = (v_015*v_015)                            (23 0)
	v_068 = (v_066+v_067)                            (24 0)
	i_039 = 2                                        (1 0) (a number)
	c_070 = (i_039*mu)                               (2 0)
	v_071 = (c_070*v_014)                            (25 0)
	v_072 = (v_068-v_071)                            (26 0)
	v_073 = (c_069+v_072)                            (27 0)
	c_041 = 3.                                       (3 0)
	c_074 = (-c_041)                                 (4 0)
	c_075 = (c_074/i_039)                            (5 0)
	v_076 = (v_073^c_075)                            (28 0)
	v_077 = (c_065*v_076)                            (29 0)
	v_081 = (v_014-mu)                               (30 0)
	v_133 = (v_077*v_081)                            (31 0)
	v_134 = (v_017-v_133)                            (32 0)
	c_090 = (c_065*c_065)                            (6 0)
	c_085 = (c_065*i_039)                            (7 0)
	v_086 = (c_085*v_014)                            (33 0)
	v_087 = (v_068+v_086)                            (34 0)
	v_091 = (c_090+v_087)                            (35 0)
	v_094 = (v_091^c_075)                            (36 0)
	v_095 = (mu*v_094)                               (37 0)
	v_099 = (c_065+v_014)                            (38 0)
	v_136 = (v_095*v_099)                            (39 0)
	v_137 = (v_134-v_136)                            (40 0)
	v_138 = (-v_016)                                 (41 0)
	v_125 = (v_077+v_095)                            (42 0)
	v_140 = (v_015*v_125)                            (43 0)
	v_141 = (v_138-v_140)                            (44 0)
	v_142 = (v_022+v_026)                            (45 0)
	v_143 = (v_023+v_027)                            (46 0)
	v_144 = (v_024+v_028)                            (47 0)
	v_145 = (v_025+v_029)                            (48 0)
	v_146 = (-v_018)                                 (49 0)
	v_147 = (v_030+v_146)                            (50 0)
	v_148 = (-v_019)                                 (51 0)
	v_149 = (v_031+v_148)                            (52 0)
	v_150 = (-v_020)                                 (53 0)
	v_151 = (v_032+v_150)                            (54 0)
	v_152 = (-v_021)                                 (55 0)
	v_153 = (v_033+v_152)                            (56 0)
	v_102 = (-v_077)                                 (57 0)
	i_044 = 3                                        (2 0) (a number)
	i_078 = (-i_044)                                 (3 0) (a number)
	v_079 = (i_078*v_077)                            (58 0)
	v_080 = (v_079/v_073)                            (59 0)
	v_082 = (v_080*v_081)                            (60 0)
	v_104 = (v_081*v_082)                            (61 0)
	v_105 = (v_102-v_104)                            (62 0)
	v_106 = (v_105-v_095)                            (63 0)
	v_097 = (i_078*v_095)                            (64 0)
	v_098 = (v_097/v_091)                            (65 0)
	v_100 = (v_098*v_099)                            (66 0)
	v_108 = (v_099*v_100)                            (67 0)
	v_109 = (v_106-v_108)                            (68 0)
	v_154 = (v_018*v_109)                            (69 0)
	v_083 = (v_015*v_080)                            (70 0)
	v_111 = (-v_081)                                 (71 0)
	v_112 = (v_083*v_111)                            (72 0)
	v_101 = (v_015*v_098)                            (73 0)
	v_114 = (v_099*v_101)                            (74 0)
	v_115 = (v_112-v_114)                            (75 0)
	v_155 = (v_022*v_115)                            (76 0)
	v_156 = (v_154+v_155)                            (77 0)
	v_157 = (v_030+v_156)                            (78 0)
	v_158 = (v_019*v_109)                            (79 0)
	v_159 = (v_023*v_115)                            (80 0)
	v_160 = (v_158+v_159)                            (81 0)
	v_161 = (v_031+v_160)                            (82 0)
	v_162 = (v_020*v_109)                            (83 0)
	v_163 = (v_024*v_115)                            (84 0)
	v_164 = (v_162+v_163)                            (85 0)
	v_165 = (v_032+v_164)                            (86 0)
	v_166 = (v_021*v_109)                            (87 0)
	v_167 = (v_025*v_115)                            (88 0)
	v_168 = (v_166+v_167)                            (89 0)
	v_169 = (v_033+v_168)                            (90 0)
	v_122 = (-v_015)                                 (91 0)
	v_123 = (v_082+v_100)                            (92 0)
	v_124 = (v_122*v_123)                            (93 0)
	v_170 = (v_018*v_124)                            (94 0)
	v_126 = (-v_125)                                 (95 0)
	v_127 = (v_083+v_101)                            (96 0)
	v_128 = (v_015*v_127)                            (97 0)
	v_129 = (v_126-v_128)                            (98 0)
	v_171 = (v_022*v_129)                            (99 0)
	v_172 = (v_170+v_171)                            (100 0)
	v_173 = (v_172-v_026)                            (101 0)
	v_174 = (v_019*v_124)                            (102 0)
	v_175 = (v_023*v_129)                            (103 0)
	v_176 = (v_174+v_175)                            (104 0)
	v_177 = (v_176-v_027)                            (105 0)
	v_178 = (v_020*v_124)                            (106 0)
	v_179 = (v_024*v_129)                            (107 0)
	v_180 = (v_178+v_179)                            (108 0)
	v_181 = (v_180-v_028)                            (109 0)
	v_182 = (v_021*v_124)                            (110 0)
	v_183 = (v_025*v_129)                            (111 0)
	v_184 = (v_182+v_183)                            (112 0)
	v_185 = (v_184-v_029)                            (113 0)
===================================================================
=========                                                  ========
=========          Differential Equations                  ========
=========                                                  ========
===================================================================

	 v_014'=v_130
	 v_015'=v_131
	 v_016'=v_137
	 v_017'=v_141
	 v_018'=v_142
	 v_019'=v_143
	 v_020'=v_144
	 v_021'=v_145
	 v_022'=v_147
	 v_023'=v_149
	 v_024'=v_151
	 v_025'=v_153
	 v_026'=v_157
	 v_027'=v_161
	 v_028'=v_165
	 v_029'=v_169
	 v_030'=v_173
	 v_031'=v_177
	 v_032'=v_181
	 v_033'=v_185
*/
/*************** END  END  END ***************************************/
